# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(341, 339)
        MainWindow.setStyleSheet("background-color:#2b2c2e;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(280, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.equal.setFont(font)
        self.equal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.equal.setStyleSheet("background-color:#ff9f0a;\n"
"color:#e4e4e5;")
        self.equal.setObjectName("equal")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(130, 110, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.one.setFont(font)
        self.one.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.one.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;\n"
"\n"
"")
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(180, 110, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.two.setFont(font)
        self.two.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.two.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;")
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(230, 110, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.three.setFont(font)
        self.three.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.three.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;")
        self.three.setObjectName("three")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(130, 160, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.four.setFont(font)
        self.four.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.four.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;")
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(180, 160, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.five.setFont(font)
        self.five.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.five.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;")
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(230, 160, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.six.setFont(font)
        self.six.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.six.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;")
        self.six.setObjectName("six")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(130, 210, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.seven.setFont(font)
        self.seven.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;")
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(180, 210, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.eight.setFont(font)
        self.eight.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eight.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;\n"
"")
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(230, 210, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nine.setFont(font)
        self.nine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nine.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;")
        self.nine.setObjectName("nine")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(280, 210, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add.setFont(font)
        self.add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add.setStyleSheet("background-color:#ff9f0a;\n"
"color:#e4e4e5;")
        self.add.setObjectName("add")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(280, 160, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.minus.setFont(font)
        self.minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minus.setStyleSheet("background-color:#ff9f0a;\n"
"color:#e4e4e5;")
        self.minus.setObjectName("minus")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(280, 110, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.multiply.setFont(font)
        self.multiply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.multiply.setStyleSheet("background-color:#ff9f0a;\n"
"color:#e4e4e5;")
        self.multiply.setObjectName("multiply")
        self.coma = QtWidgets.QPushButton(self.centralwidget)
        self.coma.setGeometry(QtCore.QRect(230, 260, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.coma.setFont(font)
        self.coma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.coma.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;")
        self.coma.setObjectName("coma")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(130, 260, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.zero.setFont(font)
        self.zero.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zero.setStyleSheet("background-color:#666768;\n"
"color:#e4e4e5;")
        self.zero.setObjectName("zero")
        self.input = QtWidgets.QTextEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(10, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.input.setFont(font)
        self.input.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.input.setStyleSheet("border:none;\n"
"color:#e4e4e5;")
        self.input.setReadOnly(True)
        self.input.setOverwriteMode(False)
        self.input.setObjectName("input")
        self.div = QtWidgets.QPushButton(self.centralwidget)
        self.div.setGeometry(QtCore.QRect(280, 60, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.div.setFont(font)
        self.div.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.div.setStyleSheet("background-color:#ff9f0a;\n"
"color:#e4e4e5;")
        self.div.setObjectName("div")
        self.porcent = QtWidgets.QPushButton(self.centralwidget)
        self.porcent.setGeometry(QtCore.QRect(230, 60, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.porcent.setFont(font)
        self.porcent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.porcent.setStyleSheet("background-color:#434346;\n"
"color:#e4e4e5;")
        self.porcent.setObjectName("porcent")
        self.clearall = QtWidgets.QPushButton(self.centralwidget)
        self.clearall.setGeometry(QtCore.QRect(130, 60, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clearall.setFont(font)
        self.clearall.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearall.setStyleSheet("background-color:#434346;\n"
"color:#e4e4e5;")
        self.clearall.setObjectName("clearall")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(180, 60, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clear.setFont(font)
        self.clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear.setStyleSheet("background-color:#434346;\n"
"color:#e4e4e5;")
        self.clear.setObjectName("clear")
        self.binary = QtWidgets.QPushButton(self.centralwidget)
        self.binary.setGeometry(QtCore.QRect(10, 60, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.binary.setFont(font)
        self.binary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.binary.setStyleSheet("background-color:#434346;\n"
"color:#e4e4e5;")
        self.binary.setObjectName("binary")
        self.hexadecimal = QtWidgets.QPushButton(self.centralwidget)
        self.hexadecimal.setGeometry(QtCore.QRect(10, 150, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hexadecimal.setFont(font)
        self.hexadecimal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hexadecimal.setStyleSheet("background-color:#434346;\n"
"color:#e4e4e5;")
        self.hexadecimal.setObjectName("hexadecimal")
        self.decimal = QtWidgets.QPushButton(self.centralwidget)
        self.decimal.setGeometry(QtCore.QRect(10, 230, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.decimal.setFont(font)
        self.decimal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.decimal.setStyleSheet("background-color:#434346;\n"
"color:#e4e4e5;")
        self.decimal.setObjectName("decimal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 341, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.equal.setText(_translate("MainWindow", "="))
        self.one.setText(_translate("MainWindow", "1"))
        self.two.setText(_translate("MainWindow", "2"))
        self.three.setText(_translate("MainWindow", "3"))
        self.four.setText(_translate("MainWindow", "4"))
        self.five.setText(_translate("MainWindow", "5"))
        self.six.setText(_translate("MainWindow", "6"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.add.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.multiply.setText(_translate("MainWindow", "x"))
        self.coma.setText(_translate("MainWindow", ","))
        self.zero.setText(_translate("MainWindow", "0"))
        self.div.setText(_translate("MainWindow", "÷"))
        self.porcent.setText(_translate("MainWindow", "%"))
        self.clearall.setText(_translate("MainWindow", "A/C"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.binary.setText(_translate("MainWindow", "Binary"))
        self.hexadecimal.setText(_translate("MainWindow", "Hexadecimal"))
        self.decimal.setText(_translate("MainWindow", "Decimal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

